# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gem2deb}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David A. Cuadrado"]
  s.date = %q{2009-10-17}
  s.email = %q{krawek@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION",
     "gem2deb.gemspec",
     "lib/commands/deb.rb",
     "lib/rubygems_plugin.rb",
     "lib/templates/debian/changelog",
     "lib/templates/debian/compat",
     "lib/templates/debian/control",
     "lib/templates/debian/copyright",
     "lib/templates/debian/rules",
     "lib/templates/executable",
     "test/gem2deb_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/dcu/gem2deb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Convert ruby gems to debian packages}
  s.test_files = [
    "test/test_helper.rb",
     "test/gem2deb_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
